---
# Install selected packages

- name: List user with home directory
  shell: ls -1 /home
  register: linux_users
  changed_when: false
  when: user_list == []

- name: Set linux_users to list
  set_fact:
    user_list: "{{ linux_users.stdout_lines | list + ['root'] }}"
  when: user_list == []

- name: Install os packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_packages }}"

- name: Snapd service
  service:
    name: snapd
    state: started
    enabled: yes

# - name: Install Virtualbox
#   package:
#     name: virtualbox
#     state: present
#   when: virtualbox_install
#   tags: virtualbox

# - name: Install text editor Atom
#   import_tasks: setup-atom.yml
#   when: atom_install
#   tags: atom

- name: Install awscli
  import_tasks: setup-aws-cli.yml
  when: awscli_install
  tags: awscli

- name: Install voice and text chat Discord
  import_tasks: setup-discord.yml
  when: discord_install
  tags: discord

- name: Install Docker
  import_tasks: setup-docker.yml
  when: docker_install
  tags: docker

- name: Install Kubernetes Minikube
  import_tasks: setup-minikube.yml
  when: minikube_install
  tags: minikube

- name: Install Spotify
  import_tasks: setup-spotify.yml
  when: spotify_install
  tags: spotify

- name: Install VS code
  import_tasks: setup-code.yml
  when: code_install
  tags: code